name: Docker build and push

on:
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
        run: yarn global add turbo env-cmd wait-on
      -
        name: Setup local cache registry
        uses: actions/cache@v2
        with:
          path: /tmp/docker-cache
          key: docker-${{ hashFiles('**/Dockerfile') }}
        run: |
          docker run -d -p 5000:5000 --restart=always --name registry -v /tmp/docker-cache:/var/lib/registry registry:2 && npx wait-on tcp:5000
      -
        name: Build images
        run: yarn docker-build
      - 
        name: Push images to local registry
        run: docker images --format "{{.Repository}}" | grep stoner
