name: Docker build and push

on:
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
#       - 
#         name: Setup Buildx
#         uses: docker/setup-buildx-action@v1
#         with:
#           install: true
#       - 
#         name: Setup Docker layers cache
#         uses: actions/cache@v2
#         with:
#           path: /tmp/.buildx-cache
#           key: ${{ runner.os }}-buildx-${{ github.sha }}
#           restore-keys: ${{ runner.os }}-buildx-
#       -
#         name: Login to Docker registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Install global deps
        run: yarn global add turbo env-cmd -g
      -
        name: Build containers
        run: |
          yarn docker-build
          docker images
#       -
#         name: List containers
#         run: docker images
#       -
#         name: Move cache
#         run: |
#           rm -rf /tmp/.buildx-cache
#           mv /tmp/.buildx-cache-new /tmp/.buildx-cache
