name: Docker build and push

on:
  workflow_dispatch:
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: yarn
      -
        name: Install global deps
        run: yarn global add turbo env-cmd -g
      -
        name: Build images
        run: yarn docker-build
      - 
        name: List images
        run: docker images --format "{{.Repository}}" | grep stoner
